appName: dio-app-ce # CHANGEME! lettere minuscole e trattini, no spazi!!
developerName: "smerlos"   # Il tuo nome! o di qualcuno che ti è simpatico
serverPort: 7000          # A piacere > 1000

#    Una volta completata la pipeline di CI/CD, potrai raggiungere il tuo sito web navigando su
#   <appName>.demo.k8s.cloudnative.demoreevo.it
